'use strict';
(()=>{
const items=window.ZHICHANG_ITEMS||[],sources=Object.fromEntries((window.ZHICHANG_SOURCES||[]).map(s=>[s.id,s]));
const labels={up:'向上沟通',peer:'同事协作',manage:'团队管理',self:'工作自保',talk:'表达与发展',org:'组织判断'},volumes={1:'基础应对',2:'协作进阶',3:'高阶判断与选择'};
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const controls={search:$('#search'),volume:$('#volume'),category:$('#category'),time:$('#time'),saved:$('#savedOnly')};
let saved=new Set;try{saved=new Set(JSON.parse(localStorage.getItem('zhichang-saved')||'[]').filter(n=>items.some(q=>q.id===n)))}catch{}
let active=readHash(),visible=[];
function readHash(){const n=Number(new URLSearchParams(location.hash.slice(1)).get('q'));return items.some(q=>q.id===n)?n:1}
function matches(q){const t=controls.search.value.trim().toLowerCase();return(controls.volume.value==='all'||q.volume===Number(controls.volume.value))&&(controls.category.value==='all'||q.category===controls.category.value)&&(controls.time.value==='all'||q.minutes<=Number(controls.time.value))&&(!controls.saved.checked||saved.has(q.id))&&(!t||(/^\d+$/.test(t)?q.id===Number(t):`${q.title} ${labels[q.category]} ${q.verdict} ${q.body.join(' ')} ${q.say}`.toLowerCase().includes(t)))}
function reset(){controls.search.value='';controls.volume.value=controls.category.value=controls.time.value='all';controls.saved.checked=false}
function render(sync=true){visible=items.filter(matches);if(visible.length&&!visible.some(q=>q.id===active))active=visible[0].id;if(sync&&visible.length)history.replaceState(null,'',`#q=${active}`);$('#count').textContent=`${visible.length} / 100 个问题`;
$('#questionList').innerHTML=visible.length?visible.map(q=>`<button class="question${q.id===active?' active':''}" data-question="${q.id}" ${q.id===active?'aria-current="true"':''}><span class="num">${String(q.id).padStart(2,'0')}</span><span><span class="qtitle">${esc(q.title)}</span><span class="qmeta">${labels[q.category]} · ${q.minutes<=10?'准备约10分钟内':q.minutes<=30?'准备约半小时内':'需专项准备'}${saved.has(q.id)?' · 已收藏':''}</span></span></button>`).join(''):'<div class="empty">没有匹配的问题。<br>换个关键词，或去掉一个筛选条件。</div>';renderDetail();}
function bodyHTML(q){return q.body.map(p=>{const m=p.match(/^【([^】]+)】([\s\S]*)$/);return m?`<h4>${esc(m[1])}</h4><p>${esc(m[2])}</p>`:`<p>${esc(p)}</p>`}).join('')}
function cardHTML(q){return `<details class="action-card"><summary>沟通前，填一张行动卡</summary><p class="card-note">复制这四格，先填已知事实，未知的留待核对。</p><div id="cardText">${q.worksheet.map(f=>`<p>${esc(f)}</p>`).join('')}</div><button class="small-button" data-card>复制行动卡</button></details>`}
function renderDetail(){if(!visible.length){$('#detail').innerHTML='<div class="empty"><h2>先换一个找法</h2><p>当前筛选没有结果，清空后可以回到全部100问。</p><button class="small-button" data-reset>清空筛选</button></div>';return}const q=items.find(x=>x.id===active),ev=q.reference,idx=visible.findIndex(x=>x.id===q.id);
$('#detail').innerHTML=`<div class="detail-tools"><span>第 ${String(q.id).padStart(2,'0')} 问 · ${volumes[q.volume]}</span><div class="tool-buttons"><button class="small-button" data-save aria-pressed="${saved.has(q.id)}">${saved.has(q.id)?'已收藏':'收藏'}</button><button class="small-button" data-link>复制链接</button><button class="small-button" data-print>打印</button></div></div><h2>${esc(q.title)}</h2><div class="tags"><span>${labels[q.category]}</span><span class="risk-${q.risk}">${q.risk==='high'?'涉及重要权益 / 权限':q.risk==='medium'?'需要留意关系与责任':'可以小范围尝试'}</span><span>${esc(ev.kind)}</span></div><div class="verdict"><span class="small-label">先判断，值不值得投入</span>${esc(q.verdict)}</div><div class="first-action"><span class="step-circle">1</span><div><b>今天先做这一件事</b>${esc(q.firstAction)}</div></div><div class="value-row"><div><b>要付出什么</b>${esc(q.cost)}</div><div><b>可能换回什么</b>${esc(q.gain)}</div></div><div class="section-heading"><h3>一句可以改成你自己的话</h3><button class="small-button copy-button" data-copy>复制话术</button></div><blockquote class="quote" id="quote">${esc(q.say)}</blockquote><div class="copy-status" id="copyStatus" role="status" aria-live="polite"></div><div class="reading"><details open><summary>完整拆解 · 为什么，怎样做，何时换路径</summary><div class="body-copy">${bodyHTML(q)}</div></details></div>${cardHTML(q)}<div class="boundary"><b>使用前，再看一个边界</b>${esc(q.limit)}</div><details class="reference"><summary>参考与可信范围 · ${esc(ev.kind)}</summary><p>${esc(ev.note)}</p>${ev.ruleNote?`<p>${esc(ev.ruleNote)}</p>`:''}${ev.readingNote?`<p>${esc(ev.readingNote)}</p>`:''}${ev.sourceIds.map(id=>{const s=sources[id];return `<div class="source-item"><a href="${esc(s.url)}" target="_blank" rel="noreferrer">${esc(s.title)} ↗</a><span>${esc(s.publisher)}<br>${esc(s.status)} · 核验记录 ${s.id.startsWith('ima-')?'2026-10-07':'2026-10-06'}</span></div>`}).join('')}${!ev.sourceIds.length?'<p>本题未列能验证具体建议效果的外部证据。完整来源状态见下方重构说明。</p>':''}</details><div class="related"><h3>如果你的问题还包括这些</h3>${q.related.map(n=>{const r=items.find(x=>x.id===n);return `<a href="#q=${n}" data-related="${n}">${String(n).padStart(2,'0')} · ${esc(r.title)} →</a>`}).join('')}</div><div class="pager"><button class="small-button" data-prev ${idx===0?'disabled':''}>← 上一问</button><span class="qmeta">当前筛选 ${idx+1} / ${visible.length}</span><button class="small-button" data-next ${idx===visible.length-1?'disabled':''}>下一问 →</button></div>`;}
function choose(id,{clear=false,scroll=false,push=true}={}){if(clear)reset();active=Number(id);if(push)history.pushState(null,'',`#q=${active}`);render(false);if(scroll){$('#detail').scrollIntoView({block:'start'});$('#detail').focus({preventScroll:true})}}
async function copy(text,element){const status=$('#copyStatus');try{await navigator.clipboard.writeText(text);status.textContent='已复制，可以按你的实际情况修改。'}catch{if(element){const range=document.createRange();range.selectNodeContents(element);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);status.textContent='已选中，请手动复制。'}else status.textContent='复制失败，可复制浏览器地址栏。'}}
const browse=document.createElement('button');browse.type='button';browse.className='mobile-browse small-button';browse.textContent='展开目录与筛选';browse.setAttribute('aria-expanded','false');$('.search-wrap').after(browse);browse.onclick=()=>{const expanded=$('.sidebar').classList.toggle('expanded');browse.setAttribute('aria-expanded',String(expanded));browse.textContent=expanded?'收起目录与筛选':'展开目录与筛选'};
Object.values(controls).forEach(c=>c.addEventListener(c===controls.search?'input':'change',()=>render()));$('#reset').onclick=()=>{reset();render()};
$('#questionList').onclick=e=>{const b=e.target.closest('[data-question]');if(b)choose(b.dataset.question,{scroll:matchMedia('(max-width:650px)').matches})};
document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>{reset();controls.search.value=b.dataset.start;render();$('.workspace').scrollIntoView({block:'start'})});
$('#detail').onclick=e=>{const target=e.target.closest('button,a');if(!target)return;if(target.hasAttribute('data-reset')){reset();render();return}if(target.dataset.related){e.preventDefault();choose(target.dataset.related,{clear:true,scroll:true});return}const q=items.find(x=>x.id===active);if(target.hasAttribute('data-copy'))copy(q.say,$('#quote'));if(target.hasAttribute('data-card'))copy(q.title+'\n'+q.worksheet.join('\n'),$('#cardText'));if(target.hasAttribute('data-link'))copy(location.href);if(target.hasAttribute('data-print'))window.print();if(target.hasAttribute('data-save')){saved.has(active)?saved.delete(active):saved.add(active);try{localStorage.setItem('zhichang-saved',JSON.stringify([...saved]))}catch{}render()}const idx=visible.findIndex(x=>x.id===active);if(target.hasAttribute('data-prev')&&idx>0)choose(visible[idx-1].id,{scroll:true});if(target.hasAttribute('data-next')&&idx<visible.length-1)choose(visible[idx+1].id,{scroll:true})};
$('.skip').onclick=e=>{e.preventDefault();$('#detail').scrollIntoView({block:'start'});$('#detail').focus({preventScroll:true})};
window.addEventListener('beforeprint',()=>{document.querySelectorAll('#detail details').forEach(d=>{d.dataset.printOpen=d.open?'1':'0';d.open=true})});window.addEventListener('afterprint',()=>{document.querySelectorAll('#detail details').forEach(d=>{d.open=d.dataset.printOpen==='1'})});
window.addEventListener('popstate',()=>{active=readHash();reset();render(false)});window.addEventListener('hashchange',()=>{active=readHash();reset();render(false)});
document.addEventListener('keydown',e=>{if(e.target.closest('input,select,textarea,[contenteditable=true]'))return;if(e.key==='/'){e.preventDefault();controls.search.focus()}if(e.target===$('#detail')&&(e.key==='ArrowLeft'||e.key==='ArrowRight')){const idx=visible.findIndex(q=>q.id===active),next=idx+(e.key==='ArrowRight'?1:-1);if(visible[next]){e.preventDefault();choose(visible[next].id,{scroll:true})}}});
const mobileReader=matchMedia('(max-width:650px)');new MutationObserver(()=>{if(mobileReader.matches)$('#detail .reading details')?.removeAttribute('open')}).observe($('#detail'),{childList:true});
render();if(location.hash.startsWith('#q=')&&active>1)requestAnimationFrame(()=>$('#detail').scrollIntoView({block:'start'}));
})();
